### ISSUE TITLE
Octave transposition

### ISSUE THREAD

**Issue by annawright18** [polyrhythm-project/polyrhythm-website#84] opened 2020-01-31 23:57 UTC
Woodwind parts are notated an octave too high?

Example 485 - R485_Mau-w85p12m57-60

<img width="326" alt="Screen Shot 2020-01-31 at 3 56 18 PM" src="https://user-images.githubusercontent.com/54776443/73582508-5b638300-4442-11ea-930f-6b602794b8e2.png">
<img width="415" alt="Screen Shot 2020-01-31 at 3 56 26 PM" src="https://user-images.githubusercontent.com/54776443/73582511-5d2d4680-4442-11ea-88cd-c381713968ae.png">

**Comment by craigsapp** [comment] 2020-02-01 01:16
No, only the piccolo part is too high.  This is a duplicate of issues #20/#26.  The piccolo part is notated an octave lower than sounding, and octave transposition parts need to be fixed (either in Sibelius or Humdrum or both).

**Closed by craigsapp** 2020-02-01 01:16 UTC
