### ISSUE TITLE
Slur and beam of appoggiaturas missing

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/polyrhythm-website#32] opened 2020-01-18 00:14 UTC
ex. T 329, Bartok, on VHV slurs and appoggiaturas beams are missing throughout the treble clef.

**Comment by craigsapp** [comment] 2020-01-18 17:39
Currently:

<img width="622" alt="Screen Shot 2020-01-18 at 09 24 10" src="https://user-images.githubusercontent.com/3487289/72667790-6f37cf80-39d4-11ea-9579-392ba7e3ca7e.png">

Expected

<img width="544" alt="Screen Shot 2020-01-18 at 09 24 16" src="https://user-images.githubusercontent.com/3487289/72667792-72cb5680-39d4-11ea-91a8-372297eef20a.png">

**Comment by craigsapp** [comment] 2020-01-18 17:45
This is caused by a bug in the MusicXML export from Sibelius.  

Here is the MusicXML data for the grace notes:

```xml
                        <note>
                                <grace slash='no'/>
                                <pitch>
                                        <step>E</step>
                                        <octave>5</octave>
                                </pitch>
                                <voice>1</voice>
                                <type>16th</type>
                                <stem>up</stem>
                                <staff>1</staff>
                                <notations>
                                        <slur type='start' number='1'/>
                                </notations>
                        </note>
                        <note>
                                <grace slash='no'/>
                                <pitch>
                                        <step>F</step>
                                        <octave>5</octave>
                                </pitch>
                                <voice>1</voice>
                                <type>16th</type>
                                <stem>up</stem>
                                <staff>1</staff>
                        </note>
                        <note>
                                <grace slash='no'/>
                                <pitch>
                                        <step>G</step>
                                        <octave>5</octave>
                                </pitch>
                                <voice>1</voice>
                                <type>16th</type>
                                <stem>up</stem>
                                <staff>1</staff>
                        </note>
```

The notes do not have beams encoded on them.   As a comparison, here is an example using MuseScore MusicXML export:

<img width="1184" alt="Screen Shot 2020-01-18 at 09 43 43" src="https://user-images.githubusercontent.com/3487289/72668010-0736b880-39d7-11ea-8134-cfdc40211e5f.png">

The MusicXML data for the MuseScore export of the grace notes:

```xml
      <note default-x="66.53" default-y="-20.00">
        <grace/>                
        <pitch>                 
          <step>B</step>
          <octave>4</octave>
          </pitch>              
        <voice>1</voice>        
        <type>16th</type>               
        <stem>up</stem>                 
        <beam number="1">begin</beam>
        <beam number="2">begin</beam>
        </note>                 
      <note default-x="77.49" default-y="-15.00">
        <grace/>                
        <pitch>         
          <step>C</step>
          <octave>5</octave>    
          </pitch>      
        <voice>1</voice>
        <type>16th</type>       
        <stem>up</stem>                 
        <beam number="1">continue</beam>
        <beam number="2">continue</beam>
        </note>                 
      <note default-x="88.46" default-y="-10.00">
        <grace/>                
        <pitch>
          <step>D</step>
          <octave>5</octave>
          </pitch>
        <voice>1</voice>
        <type>16th</type>
        <stem>up</stem>
        <beam number="1">end</beam>
        <beam number="2">end</beam>
        </note>
```

Notice the `<beam>` markers in this data.


I will create a tool to merge a sequence of grace notes into a beamed group to deal with the problematic MusicXML export from Sibelius.

**Comment by craigsapp** [comment] 2020-01-18 20:49
The [humlib](https://humlib.sapp.org) tool `autobeam` now has an added option (`-g`) that will fix this problem.

Example work with the fix:

https://polyrhythm.humdrum.org/example/?id=329

<img width="1268" alt="Screen Shot 2020-01-18 at 12 41 01" src="https://user-images.githubusercontent.com/3487289/72670197-cb5c1d00-39ef-11ea-8494-371cd836e52f.png">



The following TDS scores have been fixed for this problem:

```
T134_Jan-w26p35m58-67.krn
T154_Deb-w13p13m151-157.krn
T160_Deb-w7p12hI1m1-4.krn
T167_Deb-w44p8h3m15-20.krn
T169_Deb-w13p37m77-90.krn
T177_Deb-w29p46-47h24m1-6.krn
T269_Ive-w44p15m1-5.krn
T301_Fal-w1p67m127-150.krn
T304_Fal-w5p75m4-1h41m1-4.krn
T309_Fal-w6p199-201m1-h1m5.krn
T321_Fal-w10p2h2m4-h3m1.krn
T326_Bar-w5p3h2m1-3.krn
T329_Bar-w17p11s3-4.krn
T331_Bar-w24p72m3-1h27m1-2.krn
T365_Str-w7p138m2-1h198-200m1.krn
T368_Str-w13p23m1h24m1-6.krn
T379_Str-w15p11h1m1-8.krn
T384_Str-w25p11h3m1-7.krn
T445_Ber-w10p351m728-732.krn
T540_Mai-w11p3h2m3-h3m4.krn
T552_Mai-w15p24h4m1-8.krn
T597_Hon-w32p17m1h14m1-8.krn
T598_Hon-w37p2-3m2-1h1m1-5.krn
T606_Hon-w35p28m1-h1m1.krn
T618_Hin-w13p8m19-27.krn
T639_Hin-w40p48hDm1-4.krn
T677_Hin-w90p15m109-112.krn
T679_Hin-w90p51m72-79.krn
T692_Ger-w4p23m21-25.krn
T740_Mes-w18p51m24-28.krn
T749_Mes-w20p84m1-5.krn
T750_Mes-w20p103m86-88.krn
T762_Mes-w22p96h4m1-4.krn
T763_Mes-w22p99h6m1-h7m1.krn
T769_Mes-w22p267h3m1-2.krn
T772_Mes-w22p298h17m3-6.krn
T787_Mes-w27p16h19m2-3.krn
T800_Bri-w22p12-13m65-70.krn
T801_Bri-w2p16h29m1-8.krn
```

And these RDS scores were fixed:

```
R428_Var-w1p12-13h5m9-12.krn
R456B_Ber-w15p474-475m553-557.krn
R688_Ger-w3p19h14m1-3.krn
R689_Ger-w12p59m29-34.krn
R770_Mes-w22p273h7m3-6.krn
R809_Bri-w28p5m22-30.krn
```

This fix should solve this particular issue for all scores, so I will close it.

**Closed by craigsapp** 2020-01-18 20:49 UTC

**Comment by craigsapp** [comment] 2020-01-18 21:54
Problem with slur should be a separate issue (Note that Issue #27 covers slurs on grace notes/regular notes, but also is a compound issue including this sub-issue, which would be useful to split into separate issues).
